## ============================================================
## Loop Solar — EMQX Configuration
## ============================================================

node {
  name = "loopsolar@127.0.0.1"
  cookie = "loopsolar_emqx_cookie"
}

## Listeners
listeners.tcp.default {
  bind = "0.0.0.0:1883"
  max_connections = 1024
}

listeners.ws.default {
  bind = "0.0.0.0:8083"
  max_connections = 512
}

## Dashboard
dashboard {
  listeners.http {
    bind = 18083
  }
  default_username = "admin"
  default_password = "loopsolar_admin_2026"
}

## Authentication — Password-based
authentication = [
  {
    mechanism = password_based
    backend = built_in_database
    user_id_type = username
  }
]

## Authorization
authorization {
  no_match = deny
  deny_action = disconnect
  sources = [
    {
      type = built_in_database
    }
  ]
}
